packages:
  - apps/*
  - services/*
  - packages/*

autoInstallPeers: true

allowBuilds:
  '@prisma/engines': true
  argon2: true
  esbuild: true
  prisma: true

minimumReleaseAgeExclude:
  - '@tanstack/query-core@5.103.1'
  - '@tanstack/react-query@5.103.1'
  - prettier@3.9.7
