"""company intel and content topic

Revision ID: 0c7c48cc0573
Revises: 3e46353ceb8b
Create Date: 2026-07-22 19:16:48.603984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c7c48cc0573'
down_revision: Union[str, Sequence[str], None] = '3e46353ceb8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contact_person', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contact_linkedin', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_url', sa.String(), nullable=True))

    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.String(), nullable=False, server_default='general'))

    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.String(), nullable=False, server_default='general'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_column('topic')

    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_column('topic')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('source_url')
        batch_op.drop_column('contact_linkedin')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_person')
        batch_op.drop_column('details')

    # ### end Alembic commands ###
