"""knowledge base tables

Revision ID: 6cb91643b568
Revises: 8c4bebb168ea
Create Date: 2026-07-16 10:57:47.394638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb91643b568'
down_revision: Union[str, Sequence[str], None] = '8c4bebb168ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('embedded', sa.Boolean(), nullable=False),
    sa.Column('file_mtime', sa.Float(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_chunks')
    op.drop_table('knowledge_documents')
    # ### end Alembic commands ###
