"""content saved flag

Revision ID: 94cdcae5500c
Revises: e022d61f039e
Create Date: 2026-07-19 18:34:02.720532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94cdcae5500c'
down_revision: Union[str, Sequence[str], None] = 'e022d61f039e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saved', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_column('saved')

    # ### end Alembic commands ###
