"""focus task notes and source

Revision ID: 3e46353ceb8b
Revises: 94cdcae5500c
Create Date: 2026-07-20 12:53:29.163578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e46353ceb8b'
down_revision: Union[str, Sequence[str], None] = '94cdcae5500c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('focus_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(), nullable=False, server_default='agent'))
        batch_op.add_column(sa.Column('created_at', sa.String(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('done_at', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('focus_tasks', schema=None) as batch_op:
        batch_op.drop_column('done_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('source')
        batch_op.drop_column('note')

    # ### end Alembic commands ###
