"""news saved score

Revision ID: e022d61f039e
Revises: bf039b2400bb
Create Date: 2026-07-18 16:57:16.903889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e022d61f039e'
down_revision: Union[str, Sequence[str], None] = 'bf039b2400bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saved', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('created_at', sa.String(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('score')
        batch_op.drop_column('saved')

    # ### end Alembic commands ###
